import { services, articles, guarantee, contact } from './content.mjs'

export const escape = (value) => String(value).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))
export const routes = ['/', ...services.map(s => `/${s[0]}`), '/business/prokuratura', '/cases', '/license', '/blog', ...articles.map(a => `/blog/${a[0]}`), '/contacts', '/privacy', '/consent', '/quiz']
const button = '<a class="button" href="/quiz">Обсудить задачу →</a>'
const cards = () => services.map(s => `<a class="card" href="/${s[0]}"><span>${escape(s[1])}</span><h3>${escape(s[2])}</h3><p>${escape(s[3])}</p><b>Подробнее ↗</b></a>`).join('')
export function page(path) {
  const service = services.find(s => '/' + s[0] === path)
  const article = articles.find(a => '/blog/' + a[0] === path)
  let title = 'ЭКОДЕЗ — санитарные услуги в Архангельске'
  let body = ''
  if (path === '/') body = `<section class="hero"><div><p class="eyebrow">АРХАНГЕЛЬСК · СЕВЕРОДВИНСК · НОВОДВИНСК</p><h1>Проблема с вредителями?<br><em>Начнём с понятного плана.</em></h1><p class="intro">Обработка квартир и участков. Контроль объектов бизнеса. Обсудим историю проблемы, подготовку и стоимость до начала работ.</p>${button}<a class="quiet" href="tel:${contact.tel}">${contact.phone}</a></div><aside class="hero-note"><span>01 / СНАЧАЛА РАЗБЕРЁМСЯ</span><h2>«Уже обрабатывали.<br>Не помогло»</h2><p>Это повод разобраться в наблюдениях, а не обещать «средство сильнее». Повторное появление само по себе не доказывает резистентность.</p><a href="/klopy">Как строится работа →</a></aside></section><section id="services"><p class="eyebrow">УСЛУГИ И НАЧАЛЬНЫЕ ЦЕНЫ</p><h2>Для дома, участка и бизнеса</h2><div class="cards">${cards()}</div><p class="muted">Начальные цены владельца. Не публичная итоговая смета: состав работ, выезд и ограничения согласуются индивидуально.</p></section>`
  else if (service) { title = `${service[1]} — ЭКОДЕЗ, Архангельск`; body = `<section class="hero compact"><div><p class="eyebrow">${escape(service[1])} / ${escape(service[2])}</p><h1>${escape(service[3])}</h1><p class="intro">${escape(service[4])}</p>${button}</div><aside class="hero-note"><h2>До приезда</h2><p>${escape(service[5])}</p></aside></section>` }
  else if (article) { title = `${article[1]} — ЭКОДЕЗ`; body = `<article class="reading"><p class="eyebrow">ПОЛЕЗНО ЗНАТЬ</p><h1>${escape(article[1])}</h1><p>${escape(article[2])}</p>${button}</article>` }
  else if (path === '/blog') { title = 'Полезные материалы — ЭКОДЕЗ'; body = `<section><h1>Без универсальных обещаний</h1><div class="cards">${articles.map(a=>`<a class="card" href="/blog/${a[0]}"><h2>${escape(a[1])}</h2><b>Читать →</b></a>`).join('')}</div></section>` }
  else if (path === '/quiz') { title = 'Обсудить задачу — ЭКОДЕЗ'; body = '<section class="reading"><p class="eyebrow">ПРЕДВАРИТЕЛЬНЫЙ РАЗБОР · НЕ ОНЛАЙН-СМЕТА</p><h1>Что происходит на объекте?</h1><p>Прототип: приём ответов квиза в Telegram и Core пока не подключён. Для реального обращения позвоните по номеру внизу страницы.</p><div id="quiz"></div><noscript>Для формы нужен JavaScript. Позвоните по номеру внизу страницы.</noscript></section>' }
  else {
    const pages = {
      '/business/prokuratura': ['Получили требование по объекту?', 'Начнём с содержания требования, сроков и состояния объекта. Согласуем фактические работы и документы по их результатам. Не обещаем закрыть проверку одним договором. Состав документов и правовые формулировки — ТРЕБУЕТ ПРОВЕРКИ до публикации.'],
      '/cases': ['Ситуации из практики отрасли', 'Это обезличенные типовые ситуации, а не опубликованные результаты клиентов ЭКОДЕЗ. «Вернулись через две недели» — собираем даты и места наблюдений. «Дорого» — сравниваем состав работ и условия повторного обращения. «Уже обрабатывали» — выясняем историю и ограничения доступа. Фото, отзывы и собственные кейсы добавляются только с подтверждением и разрешением.'],
      '/license': ['Лицензия и документы', 'Лицензионные сведения владельца перед публикацией сверяются с официальным реестром. ТРЕБУЕТ ПРОВЕРКИ. Здесь пока нет подтверждения действующего статуса лицензии.'],
      '/contacts': ['Связаться с ЭКОДЕЗ', `Архангельск, Северодвинск, Новодвинск и область. ${contact.phone}. ${contact.email}. Выезд в день обращения возможен только при подтверждённом свободном времени. Стоимость дороги согласуется заранее.`],
      '/privacy': ['Обработка персональных данных — черновик', 'ТРЕБУЕТ ПРОВЕРКИ: до публикации владелец утверждает сведения об операторе, цели, основания, сроки хранения, порядок отзыва и используемых обработчиков. Локальный квиз ничего не отправляет на сервер: ответы находятся в памяти вкладки. Переход в Telegram открывает внешний сервис. Аналитические счётчики не установлены.'],
      '/consent': ['Согласие — черновик для проверки', 'ТРЕБУЕТ ПРОВЕРКИ: юридический текст согласия утверждается отдельно до подключения приёма заявок. В локальном квизе нет скрытой отправки персональных данных. Пользователь самостоятельно решает, какие сведения отправить в Telegram.'],
    }
    const p = pages[path]
    title = p ? `${p[0]} — ЭКОДЕЗ` : 'Страница не найдена — ЭКОДЕЗ'
    body = `<section class="reading"><h1>${escape(p ? p[0] : 'Страница не найдена')}</h1><p>${escape(p ? p[1] : 'Перейдите на главную и выберите услугу.')}</p>${button}</section>`
  }
  return {title, description: service ? service[4] : 'Санитарные услуги для дома и бизнеса. Подготовка, состав работ и стоимость — по согласованию.', html: `<div class="draft">ЛОКАЛЬНЫЙ ЧЕРНОВИК · НЕ ОПУБЛИКОВАН</div><header><a class="brand" href="/">ЭКО<span>ДЕЗ</span><small>ПОНЯТНЫЙ ПЛАН. СОГЛАСОВАННЫЕ РАБОТЫ.</small></a><nav aria-label="Основное меню"><a href="/#services">Услуги</a><a href="/business">Бизнесу</a><a href="/blog">Полезное</a><a href="/contacts">Контакты</a></nav><a class="phone" href="tel:${contact.tel}">${contact.phone}</a></header><main>${body}<section class="process"><p class="eyebrow">КАК ДОГОВОРИМСЯ</p><h2>Три шага без сюрпризов</h2><div class="steps"><div><b>01</b><h3>Уточняем ситуацию</h3><p>Где замечаете проблему, что уже делали, какие есть ограничения.</p></div><div><b>02</b><h3>Согласуем условия</h3><p>Объём, стоимость, подготовку и возможное время визита.</p></div><div><b>03</b><h3>Обсуждаем контроль</h3><p>Рекомендации и условия повторного обращения фиксируем заранее.</p></div></div></section><section class="guarantee"><h2>Честно о результате</h2><p>${escape(guarantee)}</p></section></main><footer><div><a class="brand" href="/">ЭКОДЕЗ</a><p>Архангельск и область</p><a href="tel:${contact.tel}">${contact.phone}</a><br><a href="mailto:${contact.email}">${contact.email}</a></div><div><a href="/license">Документы — черновик</a><a href="/privacy">Конфиденциальность</a><a href="/consent">Согласие</a><a href="/cases">Типовые ситуации</a></div></footer>`}
}
