"""leads table

Revision ID: 8167bbea123f
Revises: 2c77868079d7
Create Date: 2026-08-11 21:45:41.526687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8167bbea123f'
down_revision: Union[str, Sequence[str], None] = '2c77868079d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('external_id', sa.String(length=100), nullable=True),
    sa.Column('order_at', sa.DateTime(), nullable=True),
    sa.Column('client_name', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('area', sa.String(length=200), nullable=True),
    sa.Column('reason', sa.String(length=300), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('amount_note', sa.String(length=300), nullable=True),
    sa.Column('contract', sa.String(length=50), nullable=True),
    sa.Column('partner', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('leads')
    # ### end Alembic commands ###
